language: node_js

node_js:
  - '8'
  - '10'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

jobs:
  include:
    - stage: Nightly Release
      node_js: '10'
      script: echo "Deploying nightly builds to npm ..."
      deploy:
        provider: script
        script: echo "something"
        on:
          branch: master
